/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Formularios;

import Datos.Datos;
import Logica.consultaDatos;
import java.util.ArrayList;
import java.util.List;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author franco
 */
public class PrimeraVista extends javax.swing.JFrame {
    
    String[] columnas = {"IDENTIFICADOR", "Diccionario", "VERSION"};
    
    DefaultTableModel modelo;
    
    consultaDatos consultaD = new consultaDatos();
    
    List<Datos> data = new ArrayList<>();
  
    
    public void cargarTabla() {
        
        tblFirstView.getTableHeader().setReorderingAllowed(false);
        this.modelo.setRowCount(0);
        data.clear();
        data = (List<Datos>) consultaD.seleccionar();
        Object[] obj = new Object[3];
        for (Datos fila : data) {
            obj[0] = fila.getIdDic();
            obj[1] = fila.getNombreDic();
            obj[2] = fila.getVersionDic();
            
            this.modelo.addRow(obj);
        }
        this.tblFirstView.setModel(modelo);
        
        DefaultTableCellRenderer tcr = new DefaultTableCellRenderer();
        tcr.setHorizontalAlignment(SwingConstants.CENTER);

        tblFirstView.getColumnModel().getColumn(0).setCellRenderer(tcr); 
        tblFirstView.getColumnModel().getColumn(2).setCellRenderer(tcr);
    }
    
    /**
     * Creates new form Visualizar
     */
    public PrimeraVista() {
        this.modelo = new DefaultTableModel(columnas, 0) {
            @Override
            public boolean isCellEditable(int filas, int columnas) {
                return columnas == 3;
            }
        };
         
        initComponents();
        setLocationRelativeTo(null);
        cargarTabla();
        
       
    }

    /**
     * Creates new form NewJFrame
     */

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblFirstView = new javax.swing.JTable();
        open = new javax.swing.JButton();
        txtName = new javax.swing.JTextField();
        txtID = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 51, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblFirstView.setBackground(new java.awt.Color(204, 204, 255));
        tblFirstView.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblFirstView.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblFirstViewMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblFirstView);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, -1, 360));

        open.setText("Abrir");
        open.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openActionPerformed(evt);
            }
        });
        jPanel1.add(open, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 70, -1, -1));

        txtName.setEditable(false);
        jPanel1.add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 70, 130, -1));

        txtID.setEditable(false);
        txtID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDActionPerformed(evt);
            }
        });
        jPanel1.add(txtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 70, 40, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 690, 580));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblFirstViewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblFirstViewMouseClicked
        // TODO add your handling code here:

        
         String idX = tblFirstView.getValueAt(tblFirstView.getSelectedRow(),0).toString();
         System.out.println("" + idX);
         
         String name = tblFirstView.getValueAt(tblFirstView.getSelectedRow(),1).toString();
         System.out.println("" + name);
         
         this.txtID.setText(idX);
         this.txtName.setText(name);
         
                 
    }//GEN-LAST:event_tblFirstViewMouseClicked
      
    
    
    private void openActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openActionPerformed
       
       Visualizar frmVis = new Visualizar();
       
       frmVis.txtIDX.setText(txtID.getText());
       
       frmVis.txtLenguaje.setText(txtName.getText());
       
       frmVis.setVisible(true);
      
    }//GEN-LAST:event_openActionPerformed

    
    private void txtIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDActionPerformed
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrimeraVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrimeraVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrimeraVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrimeraVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrimeraVista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton open;
    private javax.swing.JTable tblFirstView;
    public javax.swing.JTextField txtID;
    public javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables
}