/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Formularios;

import Datos.ItemsMenusDatos;
import Datos.Vvisual;
import Logica.consultasForm2;
import Logica.consultasVvisual;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author franco
 */
public class Visualizar extends javax.swing.JFrame {

    String[] columnas = {"ID", "Nombre Menu", "IDENTIFICADOR"};
    
    DefaultTableModel modelo;
   
    consultasForm2 consulta = new consultasForm2();
    consultasVvisual consulta2 = new consultasVvisual();
    
    
 
    Vvisual t = new Vvisual();
    List<ItemsMenusDatos> data = new ArrayList<>();
    
    public void cargarTabla() {
        
        tablaCodigo.getTableHeader().setReorderingAllowed(false);
        this.modelo.setRowCount(0);
        data.clear();
        data = (List<ItemsMenusDatos>) consulta.seleccionar();
        Object[] obj = new Object[3];
        for (ItemsMenusDatos fila : data) {
            obj[0] = fila.getIdMenu();
            obj[1] = fila.getNombreMenu();
            obj[2] = fila.getIdDic().getIdDic();
            
            this.modelo.addRow(obj);
        }
        this.tablaCodigo.setModel(modelo);
        
        DefaultTableCellRenderer tcr = new DefaultTableCellRenderer();
        tcr.setHorizontalAlignment(SwingConstants.CENTER);

        tablaCodigo.getColumnModel().getColumn(0).setCellRenderer(tcr); 
        tablaCodigo.getColumnModel().getColumn(2).setCellRenderer(tcr);
        
        
    }
    
    /**
     * Creates new form Visualizar
     */
    public Visualizar() {
        this.modelo = new DefaultTableModel(columnas, 0) {
            @Override
            public boolean isCellEditable(int filas, int columnas) {
                return columnas == 3;
            }
        };
         
        initComponents();
        setLocationRelativeTo(null);
        cargarTabla();
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaCodigo = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        txtIDX = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtAreaCode = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        txtLenguaje = new javax.swing.JTextField();
        jRadioButton1 = new javax.swing.JRadioButton();
        btnTxtSave = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Liberation Sans", 1, 15), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));
        jPanel2.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tablaCodigo.setBackground(new java.awt.Color(204, 204, 204));
        tablaCodigo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Title 1", "Title 2"
            }
        ));
        tablaCodigo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaCodigoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaCodigo);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 56, 300, 630));

        jLabel2.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Seleccionar diccionario ");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 250, -1));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 270, 20));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 310, 690));

        txtIDX.setEditable(false);
        txtIDX.setBackground(new java.awt.Color(102, 204, 255));
        jPanel1.add(txtIDX, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 50, 30, 30));

        jLabel1.setBackground(new java.awt.Color(255, 255, 204));
        jLabel1.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("#ID");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 50, -1, -1));

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        txtAreaCode.setBackground(new java.awt.Color(51, 51, 51));
        txtAreaCode.setColumns(20);
        txtAreaCode.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        txtAreaCode.setForeground(new java.awt.Color(204, 204, 204));
        txtAreaCode.setRows(5);
        jScrollPane2.setViewportView(txtAreaCode);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 656, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 606, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 100, 670, 620));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Titulo");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 50, -1, -1));

        txtLenguaje.setEditable(false);
        txtLenguaje.setBackground(new java.awt.Color(0, 204, 255));
        jPanel1.add(txtLenguaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 50, 190, 30));

        jRadioButton1.setBackground(new java.awt.Color(0, 102, 102));
        jRadioButton1.setForeground(new java.awt.Color(255, 255, 204));
        jRadioButton1.setText("Activar edicion");
        jPanel1.add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 50, -1, 30));

        btnTxtSave.setText("Guardar");
        btnTxtSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTxtSaveActionPerformed(evt);
            }
        });
        jPanel1.add(btnTxtSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 60, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1050, 730));

        jMenu1.setText("File");

        jMenuItem1.setText("Crear un proecto");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tablaCodigoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaCodigoMouseClicked
        // TODO add your handling code here:
        
       /**  this.txtIDX.setText(tablaCodigo.getValueAt(
        tablaCodigo.getSelectedRow(),2).toString());
        
        this.txtLenguaje.setText(tablaCodigo.getValueAt(
        tablaCodigo.getSelectedRow(),1).toString());*/
        
        
         String idX = tablaCodigo.getValueAt(tablaCodigo.getSelectedRow(),2).toString();
         System.out.println("" + idX);
    }//GEN-LAST:event_tablaCodigoMouseClicked

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        Editar edit = new Editar();
        edit.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void btnTxtSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTxtSaveActionPerformed
        // TODO add your handling code here:
         if(txtIDX.getText().equals("") || txtLenguaje.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Se debe seleccionar");
        }else{
            this.t.setCodex(this.txtAreaCode.getText());
           
            this.t.setIdMenu(new ItemsMenusDatos(Integer.parseInt(this.txtIDX.getText())));
            
            if(consulta2.insert(this.t)) {
                JOptionPane.showMessageDialog(this, "Registro guardado correctamente!!");
                cargarTabla(); 
            }else {
                JOptionPane.showMessageDialog(this, "Error al insertar");
            }
        }
    }//GEN-LAST:event_btnTxtSaveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Visualizar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Visualizar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Visualizar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Visualizar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Visualizar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTxtSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable tablaCodigo;
    private javax.swing.JTextArea txtAreaCode;
    public javax.swing.JTextField txtIDX;
    public javax.swing.JTextField txtLenguaje;
    // End of variables declaration//GEN-END:variables

    public String txtIDX() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
